[package]
name = "wf-engine"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "wf_engine"

[dependencies]
wf-config = { path = "../wf-config" }
wf-lang = { path = "../wf-lang" }
wf-cep = { path = "../wf-cep" }
wp-connector-api = { workspace = true }
wp-model-core = { workspace = true }
arrow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
smol_str = { workspace = true }
foldhash = { workspace = true }
parking_lot = "0.12"
async-trait = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
tokio-util = { version = "0.7", features = ["rt"] }
log = { workspace = true }
orion-error = { workspace = true }
derive_more = { workspace = true }
thiserror = { workspace = true }
sha2 = { workspace = true }
md5 = { workspace = true }
sha1 = { workspace = true }
hex = { workspace = true }
regex = { workspace = true }
wildmatch = { workspace = true }
chrono = { workspace = true }
moju-derive = { workspace = true }
redb = "4"

[dev-dependencies]
arrow = { workspace = true }
tokio = { workspace = true, features = ["rt", "macros", "time"] }

[features]
mem_test = []
